from io import BytesIO

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)


class PDFGenerator:

    def add_section(
        self,
        story,
        styles,
        title: str,
        items: list[str],
    ):
        """
        Adds a titled section with bullet-point items.
        """

        story.append(
            Paragraph(
                f"<b>{title}</b>",
                styles["Heading2"],
            )
        )

        for item in items:
            story.append(
                Paragraph(
                    f"• {item}",
                    styles["Normal"],
                )
            )

        story.append(
            Spacer(
                1,
                12,
            )
        )

    def build_resume_report(
        self,
        analysis,
    ):
        """
        Generates a professional PDF report for a resume analysis.

        Returns:
            BytesIO: PDF stored in memory.
        """

        buffer = BytesIO()

        doc = SimpleDocTemplate(
            buffer,
        )

        styles = getSampleStyleSheet()

        story = []

        # -----------------------------
        # Header
        # -----------------------------

        story.append(
            Paragraph(
                "PrepGenius AI",
                styles["Title"],
            )
        )

        story.append(
            Paragraph(
                "Resume Analysis Report",
                styles["Heading2"],
            )
        )

        story.append(
            Spacer(
                1,
                20,
            )
        )

        # -----------------------------
        # Resume Information
        # -----------------------------

        story.append(
            Paragraph(
                f"<b>Filename:</b> {analysis.filename}",
                styles["Normal"],
            )
        )

        story.append(
            Paragraph(
                f"<b>Resume Score:</b> {analysis.resume_score}/100",
                styles["Normal"],
            )
        )

        story.append(
            Paragraph(
                f"<b>Generated:</b> {analysis.created_at.strftime('%d %b %Y %I:%M %p')}",
                styles["Normal"],
            )
        )

        story.append(
            Spacer(
                1,
                20,
            )
        )

        # -----------------------------
        # Resume Sections
        # -----------------------------

        self.add_section(
            story,
            styles,
            "Technical Skills",
            analysis.technical_skills_list,
        )

        self.add_section(
            story,
            styles,
            "Soft Skills",
            analysis.soft_skills_list,
        )

        self.add_section(
            story,
            styles,
            "Strengths",
            analysis.strengths_list,
        )

        self.add_section(
            story,
            styles,
            "Weaknesses",
            analysis.weaknesses_list,
        )

        self.add_section(
            story,
            styles,
            "Missing Skills",
            analysis.missing_skills_list,
        )

        self.add_section(
            story,
            styles,
            "Recommended Interview Topics",
            analysis.recommended_topics_list,
        )

        # -----------------------------
        # Footer
        # -----------------------------

        story.append(
            Spacer(
                1,
                20,
            )
        )

        story.append(
            Paragraph(
                "Generated by PrepGenius AI",
                styles["Italic"],
            )
        )

        # -----------------------------
        # Build PDF
        # -----------------------------

        doc.build(story)

        buffer.seek(0)

        return buffer


pdf_generator = PDFGenerator()